
## 测试

在传统的系统编程语言中，没有集成测试功能。而 Rust 在语言层面对这个提供了支持。尽管自动化测试不能保证你的代码没有 bug，但它对于验证行为是否如预期所想是非常有用的。

下面是一个基本的测试：

```{rust}
#[test]
fn is_one_equal_to_one() {
    assert_eq!(1i, 1i);
}
```

现在看见了一个新事物：`#[test]`。在我们了解测试的机制之前，来谈一下属性。

### 属性

Rust 的测试系统使用 **属性** 来标记哪些函数是测试用例。属性可以放在任何 Rust 元素上。还记得为什么 Rust 中的大部分事物都是表达式，而 `let` 不是么？其实元素（Item）声明也不是表达式，下面是满足元素称号的事物：

* 函数
* 模块
* 类型定义
* 结构体
* 枚举
* 静态元素
* trait
* 实现体

上面列表里的东西咱们还没学完的。可以看到，函数在第一个位置。

属性可以以三种方式出现：

1. 就一个标识，属性名称。比如 `#[test]`；
2. 一个标识，后面跟着一个等号 `=` 和一个字面量。比如 `#[cfg=test]`；
3. 一个标识，后面跟着一对括号，括号里面是这个属性的参数列表，参数列表也有两种形式。比如 `#[cfg(unix, target_word_size = "32")]`；

Rust 有很多不同各类的属性，现在我们不打算讲完。在讲测试相关的属性之前，来了解一最重要的属性之一：稳定性标记。

### 稳定性属性

Rust 提供了六种属性来标识库的各个部分的不同的稳定性级别。这六个级别是：

* 不推荐：这个特性不应该被使用了，不能保证向后兼容性；
* 实验：这个特性是最近引入的，或者可能还有些波动。它可能会显著变化，甚至被遗弃。不能保证向后兼容性；
* 不稳定：这个特性还在开发中，需要更多的测试来验证稳定性。不能保证向后兼容性；
* 稳定：这个特性已经被认为是稳定的了，基本不会再变化了。保证向后兼容性；
* 冻结：这个特性非常稳定，不太可能变化了。保证向后兼容性；
* 锁定：这个特性不会再变化了，除非发现一个严重的bug。保证向后兼容性。

所有 Rust 的标准库都用这些标记来展示它们相对的稳定性，你也应该在你的代码里使用它们。还有一个关联的属性，`warn`，用来在你引入了一个标记为：不推荐，实验和不稳定级别的特性的时候，产生告警。目前，默认只有不推荐特性引用时会报警。但是一旦标准库稳定下来了，就会变成刚才说的那样。

你可以像下面这样使用 `warn`：

```{rust,ignore}
#![warn(unstable)]
```

然后，当你引入一个 crate 的时候：

```{rust,ignore}
extern crate some_crate;
```

如果那个 crate 里面标记了不稳定，你会得到警告。

你可能已经注意到了在 `warn` 属性声明的时候，`#` 后面，接了一个 `!` 号。这个 `!` 号表示这个属性作用于整个封闭的空间，而不是跟在这个属性后面的那个事物。所以，这里这个 `warn` 属性声明作用于整个 crate 本身：

```{rust,ignore}
// applies to the crate we're in
#![warn(unstable)]

extern crate some_crate;

// applies to the following `fn`.
#[test]
fn a_test() {
  // ...
}
```

### 写测试用例

让我们用测试驱动方法写一个简单的 crate。你应该知道怎么演练了，创建一个新的工程：

```{bash,ignore}
$ cd ~/projects
$ cargo new testing --bin
$ cd testing
```

然后试一试：

```{notrust,ignore}
$ cargo run
   Compiling testing v0.0.1 (file:///home/you/projects/testing)
     Running `target/testing`
Hello, world!
```

很好。Rust 的基础设施支持两种的测试用例，对应于两种不同的测试方法：在 crate 里面，做 **单元测试**。在 `tests` 目录下，做 **集成测试**。单元测试是小的专注于一点的测试，集成测试是多个单元一起测。这种习俗差异，在语法实现上，并没有什么不同。让我们创建一个 `tests` 目录：

```{bash,ignore}
$ mkdir tests
```

然后，让我们创建一个集成测试文件 `tests/lib.rs`：

```{rust,no_run}
#[test]
fn foo() {
    assert!(false);
}
```

怎么命名测试用例的函数都没有关系的，但最好是取一些望文生义的名字。然后，我们使用一个宏，`assert!` 来做一些断言。在这个例子中，我们给它 `false`，所以这个测试会失败。让我们操作一把！

```{notrust,ignore}
$ cargo test
   Compiling testing v0.0.1 (file:///home/you/projects/testing)
/home/you/projects/testing/src/main.rs:1:1: 3:2 warning: function is never used: `main`, #[warn(dead_code)] on by default
/home/you/projects/testing/src/main.rs:1 fn main() {
/home/you/projects/testing/src/main.rs:2     println!("Hello, world!")
/home/you/projects/testing/src/main.rs:3 }
     Running target/lib-654ce120f310a3a5

running 1 test
test foo ... FAILED

failures:

---- foo stdout ----
        task 'foo' failed at 'assertion failed: false', /home/you/projects/testing/tests/lib.rs:3



failures:
    foo

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured

task '<main>' failed at 'Some tests failed', /home/you/src/rust/src/libtest/lib.rs:243
```

很多输出！一点点分析吧：

```{notrust,ignore}
$ cargo test
   Compiling testing v0.0.1 (file:///home/you/projects/testing)
```

你可以用 `cargo test` 运行所有测试用例，既包括 `tests` 目录下的测试用例，也包括你的 crate 中的测试用例。

```{notrust,ignore}
/home/you/projects/testing/src/main.rs:1:1: 3:2 warning: function is never used: `main`, #[warn(dead_code)] on by default
/home/you/projects/testing/src/main.rs:1 fn main() {
/home/you/projects/testing/src/main.rs:2     println!("Hello, world!")
/home/you/projects/testing/src/main.rs:3 }
```

Rust 有一个特性叫 **lint**，它默认被用于告警死区。一个 lint 是一片检查你的代码的代码，可以告诉你一些相关的信息。在这个例子中，Rust 提醒我们写了一些永远用不到的代码：`main` 函数。当然，因为我们正在执行测试，不想执行 `main` 的。所以我们希望能够在这个时候，关闭对 `main` 函数的执行，一会儿就要讲到。现在先暂时忽略这些输出吧。

```{notrust,ignore}
     Running target/lib-654ce120f310a3a5

running 1 test
test foo ... FAILED
```

现在我们找到点感觉了。前面我们说过，测试的时候要取一个好点的名字。这里就找到原因了。写什么名字，在这个结果输出里面，就会报什么名字，如果名字能够忘文生义，在测试结果的报告中就会更加清晰，特别是当我们积累了大量的测试用例的时候。

```{notrust,ignore}
failures:

---- foo stdout ----
        task 'foo' failed at 'assertion failed: false', /home/you/projects/testing/tests/lib.rs:3



failures:
    foo

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured

task '<main>' failed at 'Some tests failed', /home/you/src/rust/src/libtest/lib.rs:243
```

在所有测试用例运行完成后，Rust 会给出失败的用例的详尽输出。在这个例子中，Rust 告诉我们断言失败了，这正是我们想要的。

好，来修正我们的用例吧：

```{rust}
#[test]
fn foo() {
    assert!(true);
}
```

再次运行 `cargo test`：

```{notrust,ignore}
$ cargo test
   Compiling testing v0.0.1 (file:///home/you/projects/testing)
     Running target/lib-654ce120f310a3a5

running 1 test
test foo ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured

     Running target/testing-6d7518593c7c3ee5

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured
```

很好！测试通过了，如我们所料。注意，这次没有报 `main` 的警告。是因为 `src/main.rs` 没有再编译。如果我们重新编译那个文件，又会看到警告。为了彻底去除那个警告，改一下 `src/main.rs`：

```{rust}
#[cfg(not(test))]
fn main() {
    println!("Hello, world!")
}
```

这个属性由两部分组成：`cfg` 和 `not`。`cfg` 属性让我们可以基于某些东西条件性地编译代码。跟在这个标记后面的代码只会在这个配置结果为 true 的时候才会被编译。当 Cargo 编译我们的测试用例时，它会自动设置 `cfg(test)` 为 true。 而中间加一个 `not`，就能够让 `cfg(not(test))` 结果为 false。所以，跟在后面的 `main` 函数就不会被编译了。

```{notrust,ignore}
$ cargo test
   Compiling testing v0.0.1 (file:///home/you/projects/testing)
     Running target/lib-654ce120f310a3a5

running 1 test
test foo ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured

     Running target/testing-6d7518593c7c3ee5

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured
```
好了，让我们写一个真实的测试用例吧。修改 `tests/lib.rs` 如下：

```{rust,ignore}
#[test]
fn math_checks_out() {
    let result = add_three_times_four(5i);

    assert_eq!(32i, result);
}
```

试运行一下：

```{notrust,ignore}
$ cargo test
   Compiling testing v0.0.1 (file:///home/you/projects/testing)
/home/you/projects/testing/tests/lib.rs:3:18: 3:38 error: unresolved name `add_three_times_four`.
/home/you/projects/testing/tests/lib.rs:3     let result = add_three_times_four(5i);
                                                           ^~~~~~~~~~~~~~~~~~~~
error: aborting due to previous error
Build failed, waiting for other jobs to finish...
Could not compile `testing`.

To learn more, run the command again with --verbose.
```

Rust 找不到这个函数，这就对了，我们都还没写的嘛！

为了与测试用例共享代码，我们需要写一个库 crate。这是一个很好的软件设计：将大部分代码放到一个独立的 crate 中，让可执行文件调用这个库。这可以提高代码重用。

为了做到这个，我们得创建一个新的模块。建立一个新文件，`src/lib.rs`，在里面放下面代码：

```{rust}
# fn main() {}
pub fn add_three_times_four(x: int) -> int {
    (x + 3) * 4
}
```

把这个文件命名成 `lib.rs` 是因为按习惯要与项目名称保持相同。

然后就在 `src/main.rs` 中使用这个 crate：

```{rust,ignore}
extern crate testing;

#[cfg(not(test))]
fn main() {
    println!("Hello, world!")
}
```

最后，在 `tests/lib.rs` 中引入这个函数：

```{rust,ignore}
extern crate testing;
use testing::add_three_times_four;

#[test]
fn math_checks_out() {
    let result = add_three_times_four(5i);

    assert_eq!(32i, result);
}
```

运行一下：

```{ignore,notrust}
$ cargo test
   Compiling testing v0.0.1 (file:///home/you/projects/testing)
     Running target/lib-654ce120f310a3a5

running 1 test
test math_checks_out ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured

     Running target/testing-6d7518593c7c3ee5

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured

     Running target/testing-8a94b31f7fd2e8fe

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured

   Doc-tests testing

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured
```

很好！测试通过了。我们已经完成了集成测试，表明我们的公用方法能工作，但是我们可能还想测一些内部的逻辑。尽管这个函数很简单，但是一旦变复杂后，你能想象到是需要更多的测试的。所以让我们把它切成两个辅助函数，然后分别写测试用例。

修改 `src/lib.rs` 成下面这个样子：

```{rust,ignore}
pub fn add_three_times_four(x: int) -> int {
    times_four(add_three(x))
}

fn add_three(x: int) -> int { x + 3 }

fn times_four(x: int) -> int { x * 4 }
```

如果你运行 `cargo test`，你会得到一样的输出：

```{ignore,notrust}
$ cargo test
   Compiling testing v0.0.1 (file:///home/you/projects/testing)
     Running target/lib-654ce120f310a3a5

running 1 test
test math_checks_out ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured

     Running target/testing-6d7518593c7c3ee5

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured

     Running target/testing-8a94b31f7fd2e8fe

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured

   Doc-tests testing

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured
```

如果我们试着给这两个新函数写测试，会出问题。比如：

```{rust,ignore}
extern crate testing;
use testing::add_three_times_four;
use testing::add_three;

#[test]
fn math_checks_out() {
    let result = add_three_times_four(5i);

    assert_eq!(32i, result);
}

#[test]
fn test_add_three() {
    let result = add_three(5i);

    assert_eq!(8i, result);
}
```

会报如下错：

```{notrust,ignore}
   Compiling testing v0.0.1 (file:///home/you/projects/testing)
/home/you/projects/testing/tests/lib.rs:3:5: 3:24 error: function `add_three` is private
/home/you/projects/testing/tests/lib.rs:3 use testing::add_three;
                                              ^~~~~~~~~~~~~~~~~~~
```

对了。它是私有的。所以外部的，集成的测试不能工作。这时，我们就需要单元测试了。打开 `src/lib.rs` 加入：

```{rust,ignore}
pub fn add_three_times_four(x: int) -> int {
    times_four(add_three(x))
}

fn add_three(x: int) -> int { x + 3 }

fn times_four(x: int) -> int { x * 4 }

#[cfg(test)]
mod test {
    use super::add_three;
    use super::times_four;

    #[test]
    fn test_add_three() {
        let result = add_three(5i);

        assert_eq!(8i, result);
    }

    #[test]
    fn test_times_four() {
        let result = times_four(5i);

        assert_eq!(20i, result);
    }
}
```

跑一下：

```{ignore,notrust}
$ cargo test
   Compiling testing v0.0.1 (file:///home/you/projects/testing)
     Running target/lib-654ce120f310a3a5

running 1 test
test math_checks_out ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured

     Running target/testing-6d7518593c7c3ee5

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured

     Running target/testing-8a94b31f7fd2e8fe

running 2 tests
test test::test_times_four ... ok
test test::test_add_three ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured

   Doc-tests testing

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured
```

酷！现在我们已经有了两个内部函数的测试用例了。你可以注意到有 3 部分的输出：一个是 `src/main.rs` 的，一个是 `src/lib.rs` 的，剩下一个是 `tests/lib.rs` 的。上面的代码中，有两行比较有趣：

```{rust,ignore}
use super::add_three;
use super::times_four;
```

我们写的是一个嵌套的模块，子模块里面引用父模块，使用 `super`。子模块是允许看到父模块的私有函数的。

现在我们已经了解了 Rust 测试的基本面了。Rust 提供的测试工具是很原始的，但应付简单的情况足已。基于这个，社区有些人在构建更复杂的测试框架，但基本上都是刚刚开始。

